name: E2E Tests

on:
  pull_request:
    types: [ opened, labeled, closed ]

jobs:
  init:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
        - name: PR Comment with URL
          uses: mshick/add-pr-comment@v2
          with:
            message: |
                ## E2E Tests

                To launch E2E tests add the `e2e` label to the Pull Request.
                
                --
                Powered by [Qovery](https://www.qovery.com)!
  create-e2e-environment:
    if: ${{ github.event.label.name == 'e2e' }}
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Create and deploy Qovery environment
        env:
          QOVERY_CLI_ACCESS_TOKEN: ${{ secrets.QOVERY_CLI_ACCESS_TOKEN }}
        run: |
          # Download and install Qovery CLI
          curl -s https://get.qovery.com | bash

          echo "Organization name: ${{ vars.QOVERY_ORGANIZATION_NAME }}"
          echo "Project name: ${{ vars.QOVERY_PROJECT_NAME }}"
          echo "Blueprint name: ${{ vars.QOVERY_BLUEPRINT_ENVIRONMENT_NAME }}"

          qovery container deploy \
            --organization "${{ vars.QOVERY_ORGANIZATION_NAME }}" \
            --project "${{ vars.QOVERY_PROJECT_NAME }}" \
            --environment "${{ vars.QOVERY_BLUEPRINT_ENVIRONMENT_NAME }}" \
            --container "${{ vars.QOVERY_APPLICATION_NAME }}" \
            --tag ${{ github.sha }} \
            --watch

      - name: PR Comment with URL
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            E2E Environment created!
            --
            This is an **automatic** message by [Qovery](https://www.qovery.com)

  run-e2e-tests:
    if: ${{ github.event.label.name == 'e2e' }}
    runs-on: ubuntu-latest
    needs: create-e2e-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  delete-e2e-environment:
    if: ${{ github.event.label.name == 'e2e' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs: run-e2e-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3