name: Pipeline

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run unit tests
        run: |
          echo "Unit tests completed!"

  build-and-push-container:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build, Tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/r3m4q3r9
          ECR_REPOSITORY: todo-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  create-e2e-environment:
    runs-on: ubuntu-latest
    needs: build-and-push-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: create-e2e-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  delete-e2e-environment:
    runs-on: ubuntu-latest
    needs: run-e2e-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3