name: Pull Request init

on:
  pull_request:

jobs:
  init:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Comment with URL
        uses: mshick/add-pr-comment@v2
        with:
          message-id: e2e-init-message
          message: |
            [![Qovery Preview](https://www.qovery.com/images/logo-white.svg)](https://www.qovery.com)
            ---
            
            Add the label `e2e` to launch the E2E tests for this PR with Qovery.
            
            --
            Powered by [Qovery](https://www.qovery.com)!
